### ISSUE TITLE
监听不支持IPV6？

### ISSUE THREAD

**Issue by mx4994** [Ericwyn/miniServer#1]
简单试了下，只监听IPV4地址，IPV6没监听。

不知道你用过alist没，也可以简单分享本地文件，还能设置用户、密码之类的。推荐你试试。

**Comment by Ericwyn** [comment]
miniServer 和 alist 定位不同，alist 作为网盘中转和长期运行的文件服务器，用来分享文件，miniServer 只是用来作为临时的文件传输和http调试用

**Comment by Ericwyn** [comment]
获取系统地址的时候只拿 ipv4 的地址，不过监听的是本机的 10010 端口的情况下，你用 ipv4_address:10010 还是 ipv6_address:10010 应该都可以访问

**Comment by mx4994** [comment]
> 获取系统地址的时候只拿 ipv4 的地址，不过监听的是本机的 10010 端口的情况下，你用 ipv4_address:10010 还是 ipv6_address:10010 应该都可以访问

我试过，不行的，只监听了V4可以访问，V6无法访问。
